-- ============================================================
--  RIVALS HUB PREMIUM v3.0 -- Blox Fruits
--  GUI Premium con sistema de colores personalizables
-- ============================================================

-- [0] SERVICIOS
local Players           = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local UserInputService  = game:GetService("UserInputService")
local RunService        = game:GetService("RunService")
local TweenService      = game:GetService("TweenService")
local TeleportService   = game:GetService("TeleportService")
local LocalPlayer       = Players.LocalPlayer
local HttpService       = game:GetService("HttpService")

-- [1] SISTEMA DE COLORES PERSISTENTE
local ColorPresets = {
    {name = "Blanco Puro",       color = Color3.fromRGB(255, 255, 255)},
    {name = "Negro Mate",        color = Color3.fromRGB(30, 30, 30)},
    {name = "Gris Carbon",       color = Color3.fromRGB(80, 80, 80)},
    {name = "Azul Real",         color = Color3.fromRGB(65, 105, 225)},
    {name = "Rojo Coral",        color = Color3.fromRGB(255, 87, 87)},
    {name = "Verde Esmeralda",   color = Color3.fromRGB(46, 204, 113)},
    {name = "Azul Cielo / Cian", color = Color3.fromRGB(0, 210, 255)},
    {name = "Amarillo Mostaza",  color = Color3.fromRGB(212, 175, 55)},
    {name = "Morado Electrico",  color = Color3.fromRGB(160, 100, 255)},
    {name = "Beige / Arena",     color = Color3.fromRGB(210, 190, 160)},
}

local DEFAULT_PRIMARY   = "Amarillo Mostaza"
local DEFAULT_SECONDARY = "Morado Electrico"

local function getPresetColor(name)
    for _, p in ipairs(ColorPresets) do
        if p.name == name then return p.color end
    end
    return Color3.fromRGB(212, 175, 55)
end

local SavedPrimary   = DEFAULT_PRIMARY
local SavedSecondary = DEFAULT_SECONDARY

pcall(function()
    if not isfolder("RivalsHub") then makefolder("RivalsHub") end
    if isfile("RivalsHub/colors.json") then
        local data = HttpService:JSONDecode(readfile("RivalsHub/colors.json"))
        if data.primary then SavedPrimary = data.primary end
        if data.secondary then SavedSecondary = data.secondary end
    end
end)

local function SaveColors()
    pcall(function()
        if not isfolder("RivalsHub") then makefolder("RivalsHub") end
        writefile("RivalsHub/colors.json", HttpService:JSONEncode({
            primary = SavedPrimary,
            secondary = SavedSecondary,
        }))
    end)
end

-- [2] PALETA DE COLORES CON TINTADO DINAMICO
local function lerpColor(a, b, t)
    return Color3.new(
        a.R + (b.R - a.R) * t,
        a.G + (b.G - a.G) * t,
        a.B + (b.B - a.B) * t
    )
end

local C = {
    accent   = getPresetColor(SavedPrimary),
    accent2  = getPresetColor(SavedSecondary),
    white    = Color3.fromRGB(255, 255, 255),
    green    = Color3.fromRGB(92, 240, 176),
    red      = Color3.fromRGB(255, 70, 90),
    orange   = Color3.fromRGB(255, 170, 68),
    -- These will be generated by GenerateThemeColors:
    bg = nil, panel = nil, item = nil, itemHov = nil, border = nil, text = nil, sub = nil,
}

local function GenerateThemeColors()
    -- Primary color tints the dark backgrounds
    local ac = C.accent
    C.bg      = lerpColor(Color3.fromRGB(14, 14, 14), ac, 0.07)
    C.panel   = lerpColor(Color3.fromRGB(10, 10, 10), ac, 0.06)
    C.item    = lerpColor(Color3.fromRGB(26, 26, 26), ac, 0.09)
    C.itemHov = lerpColor(Color3.fromRGB(36, 36, 36), ac, 0.11)
    C.border  = lerpColor(Color3.fromRGB(55, 55, 55), ac, 0.14)
    -- Secondary color tints the text
    local ac2 = C.accent2
    C.text    = lerpColor(Color3.fromRGB(230, 230, 230), ac2, 0.12)
    C.sub     = lerpColor(Color3.fromRGB(120, 120, 120), ac2, 0.18)
end
GenerateThemeColors()

-- Tracking arrays for live color updates
local AccentElements = {}   -- {obj, property} se actualizan con accent
local Accent2Elements = {}  -- {obj, property} se actualizan con accent2
local ThemeElements = {}    -- {obj, property, key} se actualizan con C[key]

local function trackAccent(obj, prop)
    table.insert(AccentElements, {obj = obj, prop = prop})
end
local function trackAccent2(obj, prop)
    table.insert(Accent2Elements, {obj = obj, prop = prop})
end
local function trackTheme(obj, prop, key)
    table.insert(ThemeElements, {obj = obj, prop = prop, key = key})
end

local function ApplyColorChange()
    C.accent  = getPresetColor(SavedPrimary)
    C.accent2 = getPresetColor(SavedSecondary)
    GenerateThemeColors()
    for _, e in ipairs(AccentElements) do
        pcall(function() e.obj[e.prop] = C.accent end)
    end
    for _, e in ipairs(Accent2Elements) do
        pcall(function() e.obj[e.prop] = C.accent2 end)
    end
    for _, e in ipairs(ThemeElements) do
        pcall(function() e.obj[e.prop] = C[e.key] end)
    end
    SaveColors()
end

-- [3] INTRO SCREEN MATRIX (adaptado de krazy.lua, usa color primario)
local function RunIntro()
    local introGui = Instance.new("ScreenGui")
    local Blackout = Instance.new("Frame")
    local Title = Instance.new("TextLabel")
    local Subtitle = Instance.new("TextLabel")

    introGui.Name = "RivalsPremiumIntro"
    introGui.Parent = game:GetService("CoreGui")
    introGui.IgnoreGuiInset = true

    Blackout.Size = UDim2.new(1, 0, 1, 0)
    Blackout.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
    Blackout.BorderSizePixel = 0
    Blackout.Parent = introGui

    Title.Size = UDim2.new(1, 0, 0.5, 0)
    Title.Position = UDim2.new(0, 0, 0.25, 0)
    Title.BackgroundTransparency = 1
    Title.Text = "RIVALS HUB PREMIUM"
    Title.TextColor3 = C.accent
    Title.Font = Enum.Font.GothamBlack
    Title.TextSize = 42
    Title.TextStrokeTransparency = 0
    Title.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
    Title.ZIndex = 100
    Title.Parent = Blackout

    Subtitle.Size = UDim2.new(1, 0, 0.1, 0)
    Subtitle.Position = UDim2.new(0, 0, 0.6, 0)
    Subtitle.BackgroundTransparency = 1
    Subtitle.Text = "Cargando Premium..."
    Subtitle.TextColor3 = C.accent2
    Subtitle.Font = Enum.Font.Code
    Subtitle.TextSize = 16
    Subtitle.Parent = Blackout

    task.spawn(function()
        local maxNumbers = 100
        for i = 1, maxNumbers do
            task.spawn(function()
                while Blackout.Parent do
                    local m = Instance.new("TextLabel")
                    m.Text = tostring(math.random(0, 9))
                    m.Position = UDim2.new(math.random(), 0, math.random(), 0)
                    m.BackgroundTransparency = 1
                    local r, g, b = C.accent.R, C.accent.G, C.accent.B
                    m.TextColor3 = Color3.new(r * (math.random(60, 100)/100), g * (math.random(60, 100)/100), b * (math.random(60, 100)/100))
                    m.Font = Enum.Font.Code
                    m.TextSize = math.random(14, 24)
                    m.TextTransparency = 1
                    m.Parent = Blackout
                    local duration = math.random(5, 15) / 10
                    TweenService:Create(m, TweenInfo.new(duration/2), {TextTransparency = 0}):Play()
                    task.wait(duration)
                    TweenService:Create(m, TweenInfo.new(duration/2), {TextTransparency = 1}):Play()
                    game:GetService("Debris"):AddItem(m, duration)
                    task.wait(math.random(1, 5) / 10)
                end
            end)
        end
        task.wait(4)
        local fadeInfo = TweenInfo.new(1, Enum.EasingStyle.Linear)
        TweenService:Create(Blackout, fadeInfo, {BackgroundTransparency = 1}):Play()
        TweenService:Create(Title, fadeInfo, {TextTransparency = 1}):Play()
        TweenService:Create(Subtitle, fadeInfo, {TextTransparency = 1}):Play()
        task.wait(1)
        introGui:Destroy()
    end)
end

RunIntro()
task.wait(5)

-- [4] BYPASSES (de krazy.lua)
repeat task.wait() until game:GetService("ReplicatedStorage"):FindFirstChild("Util")
pcall(function()
    local ss = require(game:GetService("ReplicatedStorage").Util.CameraShaker.Main)
    local noop = function() return nil end
    ss.StartShake = noop; ss.ShakeOnce = noop; ss.ShakeSustain = noop
    ss.CamerShakeInstance = noop; ss.Shake = noop; ss.Start = noop
end)

-- [5] VARIABLES DE ESTADO
-- Combate
local FastAttackEnabled   = false
local FastAttackRange     = 5000
local FastAttackConnection = nil
local AimlockEnabled      = false
local AimlockVerticalOffset = 0
local TargetMode          = "NPCsPlayers"
-- Player Lock
local SelectedPlayer      = nil
local TeleportEnabled     = false
local InstaTeleportEnabled = false
local SpectateEnabled     = false
local TeleportConnection  = nil
local InstaTpConnection   = nil
local SpectateConnection  = nil
local ActiveTween         = nil
local YOffset             = 0
local TweenSpeedVal       = 350
local OrbitEnabled        = false
local OrbitDistance        = 5
local OrbitHeight         = 2
local rot                 = 0
-- Funciones Extra
local FruitAttackKitsune  = false
local FruitAttackTRex     = false
local AutoAwakening       = false
local v4Connection        = nil
-- Visual
local ESPEnabled          = false
local ESPObjects          = {}
local ESPDrawingEnabled   = false
local FullBrightEnabled   = false
-- Movimiento
local iJ                  = false
local ncl                 = false
local walkWaterEnabled    = false
local sVal                = 16
local sAct                = false
local flyGui              = nil
-- Aimlock internals
local u4                  = false
local u19                 = nil

-- Red
local Net            = ReplicatedStorage:WaitForChild("Modules"):WaitForChild("Net")
local RegisterHit    = Net["RE/RegisterHit"]
local RegisterAttack = Net["RE/RegisterAttack"]

-- [6] LOGICA ESP (de Rivals(1))
local function CreateESP(target)
    if not target:FindFirstChild("Head") then return end
    local billboard = Instance.new("BillboardGui")
    billboard.Name = "RivalsPremiumESP"
    billboard.Adornee = target:FindFirstChild("Head")
    billboard.Size = UDim2.new(0, 100, 0, 40)
    billboard.StudsOffset = Vector3.new(0, 2, 0)
    billboard.AlwaysOnTop = true
    billboard.Parent = target:FindFirstChild("Head")
    local lbl = Instance.new("TextLabel")
    lbl.BackgroundTransparency = 1
    lbl.Size = UDim2.new(1, 0, 1, 0)
    lbl.Text = target.Name
    lbl.Font = Enum.Font.GothamBold
    lbl.TextSize = 13
    lbl.TextColor3 = target:IsA("Model") and C.accent or C.white
    lbl.TextStrokeTransparency = 0.4
    lbl.Parent = billboard
    table.insert(ESPObjects, billboard)
end

local function ClearESP()
    for _, obj in pairs(ESPObjects) do
        if obj then pcall(function() obj:Destroy() end) end
    end
    ESPObjects = {}
end

local function UpdateESP()
    ClearESP()
    if not ESPEnabled then return end
    for _, p in pairs(Players:GetPlayers()) do
        if p ~= LocalPlayer and p.Character then CreateESP(p.Character) end
    end
    local enemies = workspace:FindFirstChild("Enemies")
    if enemies then
        for _, npc in pairs(enemies:GetChildren()) do CreateESP(npc) end
    end
end

-- [7] LOGICA AIMLOCK (de Rivals(1))
local function FindNearestEnemy()
    local _huge = math.huge
    local screenCenter = Vector2.new(
        game:GetService("GuiService"):GetScreenResolution().X / 2,
        game:GetService("GuiService"):GetScreenResolution().Y / 2
    )
    local nearest = nil
    for _, v in ipairs(Players:GetPlayers()) do
        if v ~= LocalPlayer then
            local char = v.Character
            if char and char:FindFirstChild("HumanoidRootPart") and char:FindFirstChild("Humanoid") and char.Humanoid.Health > 0 then
                local pos, onScreen = workspace.CurrentCamera:WorldToViewportPoint(char.HumanoidRootPart.Position)
                if onScreen then
                    local dist = (screenCenter - Vector2.new(pos.X, pos.Y)).Magnitude
                    if dist < _huge then
                        nearest = char.HumanoidRootPart
                        _huge = dist
                    end
                end
            end
        end
    end
    return nearest
end

RunService.Heartbeat:Connect(function()
    if not AimlockEnabled then return end
    if u4 == true and u19 then
        local cam = workspace.CurrentCamera
        local targetPos = u19.Position + Vector3.new(0, AimlockVerticalOffset, 0)
        cam.CFrame = CFrame.new(cam.CFrame.p, targetPos)
    end
end)

-- [8] LOGICA DE ATAQUE (de Rivals(1))
local function AttackMultipleTargets(targets)
    pcall(function()
        if not targets or #targets == 0 then return end
        local allTargets = {}
        for _, targetChar in pairs(targets) do
            local head = targetChar:FindFirstChild("Head")
            if head then table.insert(allTargets, {targetChar, head}) end
        end
        if #allTargets == 0 then return end
        RegisterAttack:FireServer(0)
        RegisterHit:FireServer(allTargets[1][2], allTargets)
    end)
end

local function StopFastAttack()
    if FastAttackConnection then
        task.cancel(FastAttackConnection)
        FastAttackConnection = nil
    end
end

local function StartFastAttack()
    StopFastAttack()
    FastAttackConnection = task.spawn(function()
        while FastAttackEnabled do
            task.wait(0.005)
            pcall(function()
                local myChar = LocalPlayer.Character
                local myHRP  = myChar and myChar:FindFirstChild("HumanoidRootPart")
                if not myHRP then return end
                local range = FastAttackRange
                local targets = {}

                if TargetMode == "NPCsPlayers" or TargetMode == "OnlyPlayers" then
                    for _, player in pairs(Players:GetPlayers()) do
                        if player ~= LocalPlayer and player.Character then
                            local hum = player.Character:FindFirstChild("Humanoid")
                            local hrp = player.Character:FindFirstChild("HumanoidRootPart")
                            if hum and hrp and hum.Health > 0 and (hrp.Position - myHRP.Position).Magnitude <= range then
                                table.insert(targets, player.Character)
                            end
                        end
                    end
                end

                if TargetMode == "NPCsPlayers" or TargetMode == "OnlyNPCs" then
                    local enemies = workspace:FindFirstChild("Enemies")
                    if enemies then
                        for _, npc in pairs(enemies:GetChildren()) do
                            local hum = npc:FindFirstChild("Humanoid")
                            local hrp = npc:FindFirstChild("HumanoidRootPart")
                            if hum and hrp and hum.Health > 0 and (hrp.Position - myHRP.Position).Magnitude <= range then
                                table.insert(targets, npc)
                            end
                        end
                    end
                end

                if #targets > 0 then AttackMultipleTargets(targets) end
            end)
        end
    end)
end

-- [9] FUNCIONES DE MOVIMIENTO (de krazy.lua)
local function GetPlayerList()
    local list = {}
    for _, p in pairs(Players:GetPlayers()) do
        if p ~= LocalPlayer then table.insert(list, p.Name) end
    end
    if #list == 0 then return {"Ninguno"} end
    return list
end

local function SetNoCollide()
    pcall(function()
        if not LocalPlayer.Character then return end
        for _, v in ipairs(LocalPlayer.Character:GetChildren()) do
            if v:IsA("BasePart") then v.CanCollide = false end
        end
    end)
end

local function SetCollide()
    pcall(function()
        if not LocalPlayer.Character then return end
        for _, v in ipairs(LocalPlayer.Character:GetChildren()) do
            if v:IsA("BasePart") then v.CanCollide = true end
        end
    end)
end

local function GetNearestPlayer()
    local nearest, dist = nil, math.huge
    local myHRP = LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
    if not myHRP then return nil end
    for _, v in pairs(Players:GetPlayers()) do
        if v ~= LocalPlayer and v.Character and v.Character:FindFirstChild("HumanoidRootPart") then
            local d = (myHRP.Position - v.Character.HumanoidRootPart.Position).Magnitude
            if d < dist then dist = d; nearest = v end
        end
    end
    return nearest
end

local function TweenTP(targetHRP)
    if not LocalPlayer.Character or not LocalPlayer.Character:FindFirstChild("HumanoidRootPart") then return end
    local HRP = LocalPlayer.Character.HumanoidRootPart
    local targetPos = targetHRP.Position + Vector3.new(0, YOffset, 0)
    if targetPos.Y < 10 then targetPos = Vector3.new(targetPos.X, 10, targetPos.Z) end
    local targetCFrame = CFrame.new(targetPos)
    local Distance = (targetCFrame.Position - HRP.Position).Magnitude
    if ActiveTween then ActiveTween:Cancel() end
    ActiveTween = TweenService:Create(HRP, TweenInfo.new(Distance / TweenSpeedVal, Enum.EasingStyle.Linear), {CFrame = targetCFrame})
    ActiveTween:Play()
end

-- ============================================================
--  GUI HELPERS
-- ============================================================
local function corner(r, p)
    local c = Instance.new("UICorner", p); c.CornerRadius = UDim.new(0, r); return c
end

local function stroke(color, thickness, p)
    local s = Instance.new("UIStroke", p); s.Color = color; s.Thickness = thickness or 1; return s
end

local function label(props, parent)
    local l = Instance.new("TextLabel", parent)
    l.BackgroundTransparency = 1
    l.Font      = props.Font or Enum.Font.Gotham
    l.TextSize  = props.TextSize or 13
    l.TextColor3 = props.TextColor3 or C.text
    l.Text      = props.Text or ""
    l.Size      = props.Size or UDim2.new(1,0,1,0)
    l.Position  = props.Position or UDim2.new(0,0,0,0)
    l.TextXAlignment = props.TextXAlignment or Enum.TextXAlignment.Left
    l.TextYAlignment = props.TextYAlignment or Enum.TextYAlignment.Center
    return l
end

local function tween(obj, t, props)
    TweenService:Create(obj, TweenInfo.new(t, Enum.EasingStyle.Quint), props):Play()
end

-- ============================================================
--  SCREEN GUI
-- ============================================================
local pgui = LocalPlayer:WaitForChild("PlayerGui")
if pgui:FindFirstChild("RivalsHubPremium") then pgui.RivalsHubPremium:Destroy() end

local screenGui = Instance.new("ScreenGui", pgui)
screenGui.Name = "RivalsHubPremium"
screenGui.ResetOnSpawn = false
screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
screenGui.DisplayOrder = 1

-- ============================================================
--  NOTIFICATION SYSTEM
-- ============================================================
local notifContainer = Instance.new("Frame", screenGui)
notifContainer.Size = UDim2.new(0, 250, 1, -20)
notifContainer.Position = UDim2.new(1, -260, 0, 10)
notifContainer.BackgroundTransparency = 1
local notifLayout = Instance.new("UIListLayout", notifContainer)
notifLayout.Padding = UDim.new(0, 6)
notifLayout.SortOrder = Enum.SortOrder.LayoutOrder
notifLayout.VerticalAlignment = Enum.VerticalAlignment.Top

local function addNotification(title, msg, color)
    local notif = Instance.new("Frame", notifContainer)
    notif.Size = UDim2.new(1, 0, 0, 56)
    notif.BackgroundColor3 = Color3.fromRGB(18, 16, 28)
    notif.ClipsDescendants = true
    corner(10, notif)
    stroke(color or C.accent, 1, notif)

    local accentBar = Instance.new("Frame", notif)
    accentBar.Size = UDim2.new(0, 4, 1, -8)
    accentBar.Position = UDim2.new(0, 4, 0, 4)
    accentBar.BackgroundColor3 = color or C.accent
    corner(2, accentBar)

    label({Text = title, Font = Enum.Font.GothamBold, TextSize = 12, TextColor3 = C.white,
        Size = UDim2.new(1, -22, 0, 18), Position = UDim2.new(0, 16, 0, 8)}, notif)
    label({Text = msg, Font = Enum.Font.Gotham, TextSize = 10, TextColor3 = C.sub,
        Size = UDim2.new(1, -22, 0, 16), Position = UDim2.new(0, 16, 0, 28)}, notif)

    notif.Position = UDim2.new(1, 0, 0, 0)
    tween(notif, 0.3, {Position = UDim2.new(0, 0, 0, 0)})
    task.delay(4, function()
        tween(notif, 0.3, {Position = UDim2.new(1, 0, 0, 0)})
        task.wait(0.35)
        pcall(function() notif:Destroy() end)
    end)
end

-- ============================================================
--  MAIN FRAME
-- ============================================================
local SIDEBAR_W = 140
local TITLEBAR_H = 46

local currentGuiSize = "Mediano"
local guiSizes = {
    Pequeno = {w = 440, h = 310},
    Mediano = {w = 530, h = 380},
    Grande  = {w = 620, h = 450},
}

local defW, defH = 530, 380
local mainFrame = Instance.new("Frame", screenGui)
mainFrame.Size = UDim2.new(0, defW, 0, defH)
mainFrame.Position = UDim2.new(0.5, -defW/2, 0.5, -defH/2)
mainFrame.BackgroundColor3 = C.bg
mainFrame.ClipsDescendants = true
trackTheme(mainFrame, "BackgroundColor3", "bg")
mainFrame.Active = true
mainFrame.Draggable = true
corner(10, mainFrame)
local mainStroke = stroke(C.border, 1, mainFrame)
trackTheme(mainStroke, "Color", "border")

mainFrame.BackgroundTransparency = 1
tween(mainFrame, 0.35, {BackgroundTransparency = 0})

-- TITLEBAR
local titleBar = Instance.new("Frame", mainFrame)
titleBar.Size = UDim2.new(1, 0, 0, TITLEBAR_H)
titleBar.BackgroundColor3 = C.panel
titleBar.BorderSizePixel = 0
corner(10, titleBar)
trackTheme(titleBar, "BackgroundColor3", "panel")
-- Square off bottom corners with a fill frame
local titleBarFill = Instance.new("Frame", titleBar)
titleBarFill.Size = UDim2.new(1, 0, 0, 12)
titleBarFill.Position = UDim2.new(0, 0, 1, -12)
titleBarFill.BackgroundColor3 = C.panel
trackTheme(titleBarFill, "BackgroundColor3", "panel")
titleBarFill.BorderSizePixel = 0

local titleName = label({
    Text = "Rivals Hub", Font = Enum.Font.GothamBlack, TextSize = 15, TextColor3 = C.white,
    Size = UDim2.new(0, 90, 1, 0), Position = UDim2.new(0, 12, 0, 0),
}, titleBar)

-- PREMIUM BADGE (positioned right after title text)
local premiumBadge = Instance.new("Frame", titleBar)
premiumBadge.Size = UDim2.new(0, 70, 0, 20)
premiumBadge.Position = UDim2.new(0, 106, 0.5, -10)
premiumBadge.BackgroundColor3 = C.accent
corner(8, premiumBadge)
trackAccent(premiumBadge, "BackgroundColor3")

label({Text = "PREMIUM", Font = Enum.Font.GothamBlack, TextSize = 10,
    TextColor3 = Color3.fromRGB(10, 8, 5),
    Size = UDim2.new(1, 0, 1, 0),
    TextXAlignment = Enum.TextXAlignment.Center,
}, premiumBadge)

local titleLine = Instance.new("Frame", mainFrame)
titleLine.Size = UDim2.new(1, 0, 0, 2)
titleLine.Position = UDim2.new(0, 0, 0, TITLEBAR_H)
titleLine.BackgroundColor3 = C.accent
titleLine.BorderSizePixel = 0
trackAccent(titleLine, "BackgroundColor3")

-- Close button (top-right)
local closeBtn = Instance.new("TextButton", titleBar)
closeBtn.Size = UDim2.new(0, TITLEBAR_H, 0, TITLEBAR_H)
closeBtn.Position = UDim2.new(1, -TITLEBAR_H, 0, 0)
closeBtn.Text = "X"; closeBtn.Font = Enum.Font.GothamBold; closeBtn.TextSize = 12
closeBtn.TextColor3 = C.sub; closeBtn.BackgroundTransparency = 1
closeBtn.MouseEnter:Connect(function() closeBtn.TextColor3 = C.red end)
closeBtn.MouseLeave:Connect(function() closeBtn.TextColor3 = C.sub end)

-- Minimize button (left of close)
local minBtn = Instance.new("TextButton", titleBar)
minBtn.Size = UDim2.new(0, TITLEBAR_H, 0, TITLEBAR_H)
minBtn.Position = UDim2.new(1, -TITLEBAR_H * 2, 0, 0)
minBtn.Text = "-"; minBtn.Font = Enum.Font.GothamBold; minBtn.TextSize = 16
minBtn.TextColor3 = C.sub; minBtn.BackgroundTransparency = 1
minBtn.MouseEnter:Connect(function() minBtn.TextColor3 = C.text end)
minBtn.MouseLeave:Connect(function() minBtn.TextColor3 = C.sub end)

-- SIDEBAR (ScrollingFrame to prevent overflow)
local sidebar = Instance.new("ScrollingFrame", mainFrame)
sidebar.Size = UDim2.new(0, SIDEBAR_W, 1, -TITLEBAR_H - 1)
sidebar.Position = UDim2.new(0, 0, 0, TITLEBAR_H + 1)
sidebar.BackgroundTransparency = 1
sidebar.ScrollBarThickness = 0
sidebar.CanvasSize = UDim2.new(0, 0, 0, 0)
sidebar.AutomaticCanvasSize = Enum.AutomaticSize.Y
sidebar.BorderSizePixel = 0

local sidebarLine = Instance.new("Frame", mainFrame)
sidebarLine.Size = UDim2.new(0, 1, 1, -TITLEBAR_H - 1)
sidebarLine.Position = UDim2.new(0, SIDEBAR_W, 0, TITLEBAR_H + 1)
sidebarLine.BackgroundColor3 = C.border
sidebarLine.BorderSizePixel = 0
trackTheme(sidebarLine, "BackgroundColor3", "border")

local sideLayout = Instance.new("UIListLayout", sidebar)
sideLayout.Padding = UDim.new(0, 2)
sideLayout.SortOrder = Enum.SortOrder.LayoutOrder
local sidePad = Instance.new("UIPadding", sidebar)
sidePad.PaddingTop = UDim.new(0, 8); sidePad.PaddingLeft = UDim.new(0, 8)
sidePad.PaddingRight = UDim.new(0, 8); sidePad.PaddingBottom = UDim.new(0, 8)

-- CONTENT FRAME
local contentFrame = Instance.new("ScrollingFrame", mainFrame)
contentFrame.Size = UDim2.new(1, -(SIDEBAR_W + 14), 1, -(TITLEBAR_H + 10))
contentFrame.Position = UDim2.new(0, SIDEBAR_W + 6, 0, TITLEBAR_H + 6)
contentFrame.BackgroundTransparency = 1
contentFrame.ScrollBarThickness = 3
contentFrame.ScrollBarImageColor3 = Color3.fromRGB(60, 60, 80)
contentFrame.CanvasSize = UDim2.new(0, 0, 0, 0)
contentFrame.AutomaticCanvasSize = Enum.AutomaticSize.Y
contentFrame.BorderSizePixel = 0

local contentLayout = Instance.new("UIListLayout", contentFrame)
contentLayout.Padding = UDim.new(0, 8)
contentLayout.SortOrder = Enum.SortOrder.LayoutOrder
local contentPad = Instance.new("UIPadding", contentFrame)
contentPad.PaddingTop = UDim.new(0, 8); contentPad.PaddingBottom = UDim.new(0, 10)
contentPad.PaddingRight = UDim.new(0, 8)

-- ============================================================
--  TAB SYSTEM
-- ============================================================
local pages = {}
local navButtons = {}
local currentPage = nil

local function showPage(name)
    for pageName, page in pairs(pages) do page.Visible = (pageName == name) end
    for navName, btn in pairs(navButtons) do
        if navName == name then
            btn.BackgroundTransparency = 0
            btn.BackgroundColor3 = Color3.fromRGB(22, 20, 35)
            btn.TextColor3 = C.accent2
            if btn:FindFirstChild("ActiveLine") then
                btn.ActiveLine.BackgroundColor3 = C.accent
                btn.ActiveLine.BackgroundTransparency = 0
            end
        else
            btn.BackgroundTransparency = 1
            btn.TextColor3 = C.sub
            if btn:FindFirstChild("ActiveLine") then
                btn.ActiveLine.BackgroundTransparency = 1
            end
        end
    end
    currentPage = name
end

local function createNavBtn(name, displayText)
    local btn = Instance.new("TextButton", sidebar)
    btn.Size = UDim2.new(1, 0, 0, 32)
    btn.BackgroundTransparency = 1; btn.Text = displayText
    btn.Font = Enum.Font.Gotham; btn.TextSize = 12
    btn.TextColor3 = C.sub; btn.TextXAlignment = Enum.TextXAlignment.Left
    corner(6, btn)
    local pad = Instance.new("UIPadding", btn); pad.PaddingLeft = UDim.new(0, 10)
    local activeLine = Instance.new("Frame", btn)
    activeLine.Name = "ActiveLine"
    activeLine.Size = UDim2.new(0, 3, 0.6, 0); activeLine.Position = UDim2.new(0, -6, 0.2, 0)
    activeLine.BackgroundTransparency = 1; activeLine.BorderSizePixel = 0
    corner(2, activeLine)
    btn.MouseButton1Click:Connect(function() showPage(name) end)
    btn.MouseEnter:Connect(function()
        if currentPage ~= name then tween(btn, 0.1, {BackgroundTransparency = 0.85, TextColor3 = C.text}) end
    end)
    btn.MouseLeave:Connect(function()
        if currentPage ~= name then tween(btn, 0.1, {BackgroundTransparency = 1, TextColor3 = C.sub}) end
    end)
    navButtons[name] = btn
    return btn
end

local function createPage(name)
    local frame = Instance.new("Frame", contentFrame)
    frame.Name = name; frame.Size = UDim2.new(1, 0, 0, 0)
    frame.AutomaticSize = Enum.AutomaticSize.Y
    frame.BackgroundTransparency = 1; frame.Visible = false; frame.LayoutOrder = 1
    local layout = Instance.new("UIListLayout", frame)
    layout.Padding = UDim.new(0, 7); layout.SortOrder = Enum.SortOrder.LayoutOrder
    pages[name] = frame
    return frame
end

-- ============================================================
--  UI COMPONENTS
-- ============================================================

-- Section title
local function addSectionTitle(text, parent, order)
    local f = Instance.new("Frame", parent)
    f.Size = UDim2.new(1, 0, 0, 24); f.BackgroundTransparency = 1; f.LayoutOrder = order or 0
    local accentLine = Instance.new("Frame", f)
    accentLine.Size = UDim2.new(0, 3, 0.6, 0); accentLine.Position = UDim2.new(0, 0, 0.2, 0)
    accentLine.BackgroundColor3 = C.accent; accentLine.BorderSizePixel = 0
    corner(2, accentLine); trackAccent(accentLine, "BackgroundColor3")
    local sectionLbl = label({Text = text, Font = Enum.Font.GothamBold, TextSize = 12, TextColor3 = C.text,
        Size = UDim2.new(1,-8,1,0), Position = UDim2.new(0,8,0,0), TextXAlignment = Enum.TextXAlignment.Left}, f)
    trackTheme(sectionLbl, "TextColor3", "text")
    return f
end

-- Toggle row
local function addToggleRow(titleText, subText, parent, order, callback)
    local row = Instance.new("Frame", parent)
    row.Size = UDim2.new(1, 0, 0, subText and 48 or 38)
    row.BackgroundColor3 = C.item; row.LayoutOrder = order or 1
    row.ClipsDescendants = true
    corner(8, row); local rowStroke = stroke(C.border, 1, row)
    trackTheme(row, "BackgroundColor3", "item"); trackTheme(rowStroke, "Color", "border")

    local titleLbl = label({Text = titleText, Font = Enum.Font.GothamSemibold, TextSize = 13, TextColor3 = C.text,
        Size = UDim2.new(1, -58, 0, 20), Position = UDim2.new(0, 10, 0, subText and 6 or 0),
        TextXAlignment = Enum.TextXAlignment.Left, TextYAlignment = Enum.TextYAlignment.Center}, row)
    trackTheme(titleLbl, "TextColor3", "text")

    if subText then
        local subLbl = label({Text = subText, Font = Enum.Font.Gotham, TextSize = 10, TextColor3 = C.sub,
            Size = UDim2.new(1, -58, 0, 14), Position = UDim2.new(0, 10, 0, 27),
            TextXAlignment = Enum.TextXAlignment.Left}, row)
        trackTheme(subLbl, "TextColor3", "sub")
    end

    local toggleBg = Instance.new("Frame", row)
    toggleBg.Size = UDim2.new(0, 40, 0, 22); toggleBg.Position = UDim2.new(1, -50, 0.5, -11)
    toggleBg.BackgroundColor3 = Color3.fromRGB(42, 42, 50); corner(99, toggleBg)

    local toggleKnob = Instance.new("Frame", toggleBg)
    toggleKnob.Size = UDim2.new(0, 16, 0, 16); toggleKnob.Position = UDim2.new(0, 3, 0.5, -8)
    toggleKnob.BackgroundColor3 = Color3.fromRGB(90, 90, 105); corner(99, toggleKnob)

    local isOn = false
    local function setToggle(state)
        isOn = state
        if isOn then
            tween(toggleBg, 0.15, {BackgroundColor3 = Color3.fromRGB(50, 45, 80)})
            tween(toggleKnob, 0.15, {Position = UDim2.new(0, 21, 0.5, -8), BackgroundColor3 = C.accent2})
        else
            tween(toggleBg, 0.15, {BackgroundColor3 = Color3.fromRGB(42, 42, 50)})
            tween(toggleKnob, 0.15, {Position = UDim2.new(0, 3, 0.5, -8), BackgroundColor3 = Color3.fromRGB(90, 90, 105)})
        end
        if callback then callback(isOn) end
    end

    local clickArea = Instance.new("TextButton", row)
    clickArea.Size = UDim2.new(1, 0, 1, 0); clickArea.BackgroundTransparency = 1; clickArea.Text = ""
    clickArea.MouseButton1Click:Connect(function() setToggle(not isOn) end)

    row.MouseEnter:Connect(function() row.BackgroundColor3 = C.itemHov end)
    row.MouseLeave:Connect(function() row.BackgroundColor3 = C.item end)
    return setToggle
end

-- Slider row
local function addSliderRow(titleText, minVal, maxVal, defaultVal, parent, order, callback)
    local container = Instance.new("Frame", parent)
    container.Size = UDim2.new(1, 0, 0, 50); container.BackgroundColor3 = C.item; container.LayoutOrder = order or 1
    container.ClipsDescendants = true
    corner(8, container); local sliderStroke = stroke(C.border, 1, container)
    trackTheme(container, "BackgroundColor3", "item"); trackTheme(sliderStroke, "Color", "border")

    local sliderTitle = label({Text = titleText, Font = Enum.Font.GothamSemibold, TextSize = 13, TextColor3 = C.text,
        Size = UDim2.new(0.6, -10, 0, 20), Position = UDim2.new(0, 10, 0, 5),
        TextXAlignment = Enum.TextXAlignment.Left}, container)
    trackTheme(sliderTitle, "TextColor3", "text")

    local valLabel = label({Text = tostring(defaultVal), Font = Enum.Font.GothamBold, TextSize = 13, TextColor3 = C.accent2,
        Size = UDim2.new(0.4, -10, 0, 20), Position = UDim2.new(0.6, 0, 0, 5),
        TextXAlignment = Enum.TextXAlignment.Right}, container)
    trackAccent2(valLabel, "TextColor3")

    local track = Instance.new("Frame", container)
    track.Size = UDim2.new(1, -20, 0, 5); track.Position = UDim2.new(0, 10, 0, 32)
    track.BackgroundColor3 = Color3.fromRGB(42, 42, 55); corner(99, track)

    local fill = Instance.new("Frame", track)
    fill.Size = UDim2.new((defaultVal - minVal) / (maxVal - minVal), 0, 1, 0)
    fill.BackgroundColor3 = C.accent; fill.BorderSizePixel = 0; corner(99, fill)
    trackAccent(fill, "BackgroundColor3")

    local knob = Instance.new("Frame", track)
    knob.Size = UDim2.new(0, 12, 0, 12)
    knob.Position = UDim2.new((defaultVal - minVal) / (maxVal - minVal), -6, 0.5, -6)
    knob.BackgroundColor3 = C.white; corner(99, knob)

    local currentVal = defaultVal
    local dragging = false

    local dragBtn = Instance.new("TextButton", container)
    dragBtn.Size = UDim2.new(1, -20, 0, 20); dragBtn.Position = UDim2.new(0, 10, 0, 26)
    dragBtn.BackgroundTransparency = 1; dragBtn.Text = ""

    local function updateSlider(x)
        local trackAbsX = track.AbsolutePosition.X
        local trackAbsW = track.AbsoluteSize.X
        if trackAbsW <= 0 then return end
        local pct = math.clamp((x - trackAbsX) / trackAbsW, 0, 1)
        currentVal = math.floor(minVal + pct * (maxVal - minVal))
        fill.Size = UDim2.new(pct, 0, 1, 0)
        knob.Position = UDim2.new(pct, -6, 0.5, -6)
        valLabel.Text = tostring(currentVal)
        if callback then callback(currentVal) end
    end

    dragBtn.MouseButton1Down:Connect(function()
        dragging = true
        updateSlider(UserInputService:GetMouseLocation().X)
    end)
    UserInputService.InputChanged:Connect(function(input)
        if dragging and input.UserInputType == Enum.UserInputType.MouseMovement then updateSlider(input.Position.X) end
    end)
    UserInputService.InputEnded:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then dragging = false end
    end)
    return container
end

-- Teleport button
local function addTpButton(titleText, coords, dotColor, parent, order, callback)
    local btn = Instance.new("TextButton", parent)
    btn.Size = UDim2.new(1, 0, 0, 38); btn.BackgroundColor3 = C.item; btn.Text = ""; btn.LayoutOrder = order or 1
    btn.ClipsDescendants = true
    corner(8, btn); local tpStroke = stroke(C.border, 1, btn)
    trackTheme(btn, "BackgroundColor3", "item"); trackTheme(tpStroke, "Color", "border")

    local dot = Instance.new("Frame", btn)
    dot.Size = UDim2.new(0, 8, 0, 8); dot.Position = UDim2.new(0, 10, 0.5, -4)
    dot.BackgroundColor3 = dotColor; corner(99, dot)

    local tpTitle = label({Text = titleText, Font = Enum.Font.GothamSemibold, TextSize = 12, TextColor3 = C.text,
        Size = UDim2.new(0.55, -20, 1, 0), Position = UDim2.new(0, 22, 0, 0),
        TextXAlignment = Enum.TextXAlignment.Left}, btn)
    trackTheme(tpTitle, "TextColor3", "text")
    local tpCoords = label({Text = coords, Font = Enum.Font.Code, TextSize = 9, TextColor3 = C.sub,
        Size = UDim2.new(0.45, -10, 1, 0), Position = UDim2.new(0.55, 0, 0, 0),
        TextXAlignment = Enum.TextXAlignment.Right}, btn)
    trackTheme(tpCoords, "TextColor3", "sub")

    btn.MouseEnter:Connect(function() btn.BackgroundColor3 = C.itemHov end)
    btn.MouseLeave:Connect(function() tween(btn, 0.08, {BackgroundColor3 = C.item}) end)
    btn.MouseButton1Click:Connect(function()
        tween(btn, 0.08, {BackgroundColor3 = Color3.fromRGB(30, 32, 60)})
        task.wait(0.15); tween(btn, 0.08, {BackgroundColor3 = C.item})
        if callback then callback() end
    end)
    return btn
end

-- Button row
local function addButtonRow(titleText, parent, order, callback)
    local btn = Instance.new("TextButton", parent)
    btn.Size = UDim2.new(1, 0, 0, 38); btn.BackgroundColor3 = C.item; btn.Text = ""
    btn.LayoutOrder = order or 1; btn.ClipsDescendants = true
    corner(8, btn); local btnStroke = stroke(C.border, 1, btn)
    trackTheme(btn, "BackgroundColor3", "item"); trackTheme(btnStroke, "Color", "border")

    local btnTitle = label({Text = titleText, Font = Enum.Font.GothamSemibold, TextSize = 13, TextColor3 = C.text,
        Size = UDim2.new(1, -20, 1, 0), Position = UDim2.new(0, 10, 0, 0),
        TextXAlignment = Enum.TextXAlignment.Left}, btn)
    trackTheme(btnTitle, "TextColor3", "text")

    local arrow = label({Text = ">", Font = Enum.Font.GothamBold, TextSize = 14, TextColor3 = C.sub,
        Size = UDim2.new(0, 16, 1, 0), Position = UDim2.new(1, -22, 0, 0),
        TextXAlignment = Enum.TextXAlignment.Right}, btn)

    btn.MouseEnter:Connect(function() tween(btn, 0.08, {BackgroundColor3 = C.itemHov}) end)
    btn.MouseLeave:Connect(function() tween(btn, 0.08, {BackgroundColor3 = C.item}) end)
    btn.MouseButton1Click:Connect(function()
        tween(btn, 0.08, {BackgroundColor3 = Color3.fromRGB(30, 32, 60)})
        task.wait(0.12); tween(btn, 0.08, {BackgroundColor3 = C.item})
        if callback then callback() end
    end)
    return btn
end

-- Dropdown row
local function addDropdownRow(titleText, options, parent, order, callback)
    local container = Instance.new("Frame", parent)
    container.Size = UDim2.new(1, 0, 0, 38); container.BackgroundColor3 = C.item
    container.LayoutOrder = order or 1; container.ClipsDescendants = true
    corner(8, container); local ddStroke = stroke(C.border, 1, container)
    trackTheme(container, "BackgroundColor3", "item"); trackTheme(ddStroke, "Color", "border")

    local selectedLabel = label({Text = titleText, Font = Enum.Font.GothamSemibold, TextSize = 13,
        TextColor3 = C.text, Size = UDim2.new(1, -30, 0, 38), Position = UDim2.new(0, 10, 0, 0),
        TextXAlignment = Enum.TextXAlignment.Left}, container)
    trackTheme(selectedLabel, "TextColor3", "text")

    local arrowLabel = label({Text = "v", Font = Enum.Font.GothamBold, TextSize = 11,
        TextColor3 = C.sub, Size = UDim2.new(0, 16, 0, 38), Position = UDim2.new(1, -22, 0, 0),
        TextXAlignment = Enum.TextXAlignment.Right}, container)

    local expanded = false
    local optionFrames = {}
    local baseHeight = 38
    local optionHeight = 30

    local function createOptions(opts)
        for _, f in ipairs(optionFrames) do f:Destroy() end
        optionFrames = {}
        for i, opt in ipairs(opts) do
            local optBtn = Instance.new("TextButton", container)
            optBtn.Size = UDim2.new(1, -12, 0, optionHeight)
            optBtn.Position = UDim2.new(0, 6, 0, baseHeight + (i-1) * (optionHeight + 2))
            optBtn.BackgroundColor3 = Color3.fromRGB(28, 24, 38); optBtn.Text = opt
            optBtn.Font = Enum.Font.Gotham; optBtn.TextSize = 11; optBtn.TextColor3 = C.text
            corner(5, optBtn)

            optBtn.MouseEnter:Connect(function() tween(optBtn, 0.08, {BackgroundColor3 = Color3.fromRGB(38, 34, 52)}) end)
            optBtn.MouseLeave:Connect(function() tween(optBtn, 0.08, {BackgroundColor3 = Color3.fromRGB(28, 24, 38)}) end)
            optBtn.MouseButton1Click:Connect(function()
                selectedLabel.Text = titleText .. ": " .. opt
                if callback then callback(opt) end
                expanded = false
                container.Size = UDim2.new(1, 0, 0, baseHeight)
                arrowLabel.Text = "v"
            end)
            table.insert(optionFrames, optBtn)
        end
    end
    createOptions(options)

    local headerBtn = Instance.new("TextButton", container)
    headerBtn.Size = UDim2.new(1, 0, 0, 38); headerBtn.BackgroundTransparency = 1; headerBtn.Text = ""
    headerBtn.MouseButton1Click:Connect(function()
        expanded = not expanded
        if expanded then
            local totalH = baseHeight + #optionFrames * (optionHeight + 2) + 4
            container.Size = UDim2.new(1, 0, 0, totalH)
            arrowLabel.Text = "^"
        else
            container.Size = UDim2.new(1, 0, 0, baseHeight)
            arrowLabel.Text = "v"
        end
    end)

    container.MouseEnter:Connect(function() if not expanded then tween(container, 0.08, {BackgroundColor3 = C.itemHov}) end end)
    container.MouseLeave:Connect(function() tween(container, 0.08, {BackgroundColor3 = C.item}) end)

    local function refresh(newOptions)
        createOptions(newOptions)
    end

    return {container = container, refresh = refresh}
end

-- ============================================================
--  PAGES & NAV BUTTONS (8 tabs)
-- ============================================================
local homePage     = createPage("Home")
local combatPage   = createPage("Combate")
local playerPage   = createPage("PlayerLock")
local extraPage    = createPage("FuncionesExtra")
local visualPage   = createPage("Visual")
local movePage     = createPage("Movimiento")
local tpPage       = createPage("Teleport")
local settingsPage = createPage("Settings")

createNavBtn("Home",           "  Home")
createNavBtn("Combate",        "  Combate")
createNavBtn("PlayerLock",     "  Player Lock")
createNavBtn("FuncionesExtra", "  Funciones Extra")
createNavBtn("Visual",         "  Visual")
createNavBtn("Movimiento",     "  Movimiento")
createNavBtn("Teleport",       "  Teleport")
createNavBtn("Settings",       "  Settings")

-- ============================================================
--  HOME PAGE
-- ============================================================
local banner = Instance.new("Frame", homePage)
banner.Size = UDim2.new(1, 0, 0, 80)
banner.BackgroundColor3 = C.panel
banner.ClipsDescendants = true
trackTheme(banner, "BackgroundColor3", "panel")
banner.LayoutOrder = 1; corner(10, banner)
local bannerStroke = stroke(C.border, 1, banner)
trackTheme(bannerStroke, "Color", "border")

local bannerGlow = Instance.new("Frame", banner)
bannerGlow.Size = UDim2.new(1, 0, 0, 3)
bannerGlow.Position = UDim2.new(0, 0, 0, 0)
bannerGlow.BackgroundColor3 = C.accent; bannerGlow.BorderSizePixel = 0
trackAccent(bannerGlow, "BackgroundColor3")

local bannerGlowBottom = Instance.new("Frame", banner)
bannerGlowBottom.Size = UDim2.new(1, 0, 0, 1)
bannerGlowBottom.Position = UDim2.new(0, 0, 1, -1)
bannerGlowBottom.BackgroundColor3 = C.accent; bannerGlowBottom.BorderSizePixel = 0
bannerGlowBottom.BackgroundTransparency = 0.6
trackAccent(bannerGlowBottom, "BackgroundColor3")

local iconWrap = Instance.new("Frame", banner)
iconWrap.Size = UDim2.new(0, 52, 0, 52); iconWrap.Position = UDim2.new(0, 10, 0.5, -26)
iconWrap.BackgroundColor3 = Color3.fromRGB(22, 17, 38); iconWrap.ClipsDescendants = true
corner(99, iconWrap); stroke(C.accent, 2, iconWrap)

local iconImage = Instance.new("ImageLabel", iconWrap)
iconImage.Size = UDim2.new(1, 0, 1, 0); iconImage.BackgroundTransparency = 1
iconImage.Image = "rbxassetid://127186589815047"; iconImage.ScaleType = Enum.ScaleType.Fit; iconImage.ZIndex = 10

local bannerTitle = label({Text = "RIVALS HUB PREMIUM", Font = Enum.Font.GothamBlack, TextSize = 16, TextColor3 = C.accent,
    Size = UDim2.new(1, -76, 0, 22), Position = UDim2.new(0, 70, 0, 12),
    TextXAlignment = Enum.TextXAlignment.Left}, banner)
bannerTitle.TextTruncate = Enum.TextTruncate.AtEnd
trackAccent(bannerTitle, "TextColor3")

local statusRow = Instance.new("Frame", banner)
statusRow.Size = UDim2.new(1, -76, 0, 18); statusRow.Position = UDim2.new(0, 70, 0, 38)
statusRow.BackgroundTransparency = 1

local statusDot = Instance.new("Frame", statusRow)
statusDot.Size = UDim2.new(0, 5, 0, 5); statusDot.Position = UDim2.new(0, 0, 0.5, -2)
statusDot.BackgroundColor3 = C.green; corner(99, statusDot)

label({Text = "Active", Font = Enum.Font.GothamBold, TextSize = 11, TextColor3 = C.green,
    Size = UDim2.new(0, 42, 1, 0), Position = UDim2.new(0, 8, 0, 0)}, statusRow)
label({Text = LocalPlayer.Name, Font = Enum.Font.Gotham, TextSize = 11, TextColor3 = C.sub,
    Size = UDim2.new(1, -56, 1, 0), Position = UDim2.new(0, 56, 0, 0),
    TextXAlignment = Enum.TextXAlignment.Left}, statusRow)

-- Info grid
local infoGrid = Instance.new("Frame", homePage)
infoGrid.Size = UDim2.new(1, 0, 0, 56); infoGrid.BackgroundTransparency = 1; infoGrid.LayoutOrder = 2
local gridLayout = Instance.new("UIGridLayout", infoGrid)
gridLayout.CellSize = UDim2.new(0.5, -3, 1, 0); gridLayout.CellPadding = UDim2.new(0, 6, 0, 0)

for _, d in ipairs({{"Version", "v3.0 Premium"}, {"Executor", "Delta"}}) do
    local card = Instance.new("Frame", infoGrid); card.BackgroundColor3 = C.item
    corner(8, card); local cardStroke = stroke(C.border, 1, card)
    trackTheme(card, "BackgroundColor3", "item"); trackTheme(cardStroke, "Color", "border")
    local cardSub = label({Text = d[1], Font = Enum.Font.Gotham, TextSize = 11, TextColor3 = C.sub,
        Size = UDim2.new(1,-16,0,16), Position = UDim2.new(0,8,0,8)}, card)
    trackTheme(cardSub, "TextColor3", "sub")
    local cardVal = label({Text = d[2], Font = Enum.Font.GothamBold, TextSize = 14, TextColor3 = C.accent2,
        Size = UDim2.new(1,-16,0,20), Position = UDim2.new(0,8,0,26)}, card)
    trackAccent2(cardVal, "TextColor3")
end

-- Discord row
local discordRow = Instance.new("TextButton", homePage)
discordRow.Size = UDim2.new(1, 0, 0, 36); discordRow.BackgroundColor3 = Color3.fromRGB(20, 20, 50)
discordRow.Text = ""; discordRow.LayoutOrder = 3; corner(8, discordRow)
stroke(Color3.fromRGB(60, 65, 140), 1, discordRow)
label({Text = "discord.gg/QvpGRwDdpZ", Font = Enum.Font.GothamSemibold, TextSize = 13,
    TextColor3 = C.accent2, Size = UDim2.new(1,0,1,0), TextXAlignment = Enum.TextXAlignment.Center}, discordRow)
discordRow.MouseEnter:Connect(function() tween(discordRow, 0.1, {BackgroundColor3 = Color3.fromRGB(25,25,65)}) end)
discordRow.MouseLeave:Connect(function() tween(discordRow, 0.1, {BackgroundColor3 = Color3.fromRGB(20,20,50)}) end)

-- GUI Size selector
addSectionTitle("Tamano de GUI", homePage, 4)
local sizeContainer = Instance.new("Frame", homePage)
sizeContainer.Size = UDim2.new(1, 0, 0, 40); sizeContainer.BackgroundColor3 = C.item; sizeContainer.LayoutOrder = 5
corner(8, sizeContainer); local szStroke = stroke(C.border, 1, sizeContainer)
trackTheme(sizeContainer, "BackgroundColor3", "item"); trackTheme(szStroke, "Color", "border")
local szLayout = Instance.new("UIListLayout", sizeContainer)
szLayout.FillDirection = Enum.FillDirection.Horizontal
szLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
szLayout.VerticalAlignment = Enum.VerticalAlignment.Center; szLayout.Padding = UDim.new(0, 4)
local szPad = Instance.new("UIPadding", sizeContainer)
szPad.PaddingLeft = UDim.new(0, 6); szPad.PaddingRight = UDim.new(0, 6)

local sizeButtons = {}
local function applySizeBtn(selected)
    for _, data in ipairs(sizeButtons) do
        if data.name == selected then
            data.btn.BackgroundColor3 = C.accent; data.btn.TextColor3 = C.white
        else
            data.btn.BackgroundColor3 = Color3.fromRGB(30, 30, 40); data.btn.TextColor3 = C.sub
        end
    end
end

for _, s in ipairs({
    {label = "Pequeno", w = 440, h = 310},
    {label = "Mediano", w = 530, h = 380},
    {label = "Grande",  w = 620, h = 450},
}) do
    local btn = Instance.new("TextButton", sizeContainer)
    btn.Size = UDim2.new(0, 84, 0, 26)
    btn.BackgroundColor3 = s.label == "Mediano" and C.accent or Color3.fromRGB(30, 30, 40)
    btn.TextColor3 = s.label == "Mediano" and C.white or C.sub
    btn.Text = s.label; btn.Font = Enum.Font.GothamSemibold; btn.TextSize = 11
    corner(5, btn)
    table.insert(sizeButtons, {btn = btn, name = s.label})
    btn.MouseButton1Click:Connect(function()
        currentGuiSize = s.label; applySizeBtn(s.label)
        tween(mainFrame, 0.25, {
            Size = UDim2.new(0, s.w, 0, s.h),
            Position = UDim2.new(0.5, -s.w/2, 0.5, -s.h/2),
        })
    end)
end

-- ============================================================
--  COMBATE PAGE
-- ============================================================
addSectionTitle("Ataque", combatPage, 1)

addToggleRow("Fast Attack", "Multi-objetivo", combatPage, 2, function(on)
    FastAttackEnabled = on
    if on then StartFastAttack() else StopFastAttack() end
end)

addDropdownRow("Target Mode", {"NPCs + Players", "Solo NPCs", "Solo Players"}, combatPage, 3, function(opt)
    if opt == "NPCs + Players" then TargetMode = "NPCsPlayers"
    elseif opt == "Solo NPCs" then TargetMode = "OnlyNPCs"
    else TargetMode = "OnlyPlayers" end
end)

addSectionTitle("Aimlock", combatPage, 5)

addToggleRow("Aimlock", "Q para lockear - cercano al centro", combatPage, 6, function(on)
    AimlockEnabled = on
    if on then u19 = FindNearestEnemy(); u4 = true
    else u4 = false; u19 = nil end
end)

addSliderRow("Offset Vertical", -5, 5, 0, combatPage, 7, function(val)
    AimlockVerticalOffset = val
end)

-- ============================================================
--  PLAYER LOCK PAGE (de krazy.lua + Azucar hub)
-- ============================================================
addSectionTitle("Seleccion de Jugador", playerPage, 1)

local playerDropdown = addDropdownRow("Jugador", GetPlayerList(), playerPage, 2, function(opt)
    if opt == "Ninguno" then SelectedPlayer = nil
    else SelectedPlayer = opt end
end)

addButtonRow("Refrescar Lista", playerPage, 3, function()
    playerDropdown.refresh(GetPlayerList())
    addNotification("Player Lock", "Lista actualizada", C.green)
end)

addSectionTitle("Seguimiento", playerPage, 4)

addToggleRow("Tween to Player", "Movimiento suave con prediccion", playerPage, 5, function(v)
    TeleportEnabled = v
    if v then
        TeleportConnection = RunService.Heartbeat:Connect(function()
            if SelectedPlayer then
                local target = Players:FindFirstChild(SelectedPlayer)
                if target and target.Character and target.Character:FindFirstChild("HumanoidRootPart") then
                    TweenTP(target.Character.HumanoidRootPart)
                    SetNoCollide()
                end
            end
        end)
    else
        if TeleportConnection then TeleportConnection:Disconnect(); TeleportConnection = nil end
        if ActiveTween then ActiveTween:Cancel(); ActiveTween = nil end
        SetCollide()
    end
end)

addSliderRow("Tween Speed", 50, 350, 350, playerPage, 6, function(val)
    TweenSpeedVal = val
end)

addToggleRow("Insta TP", "Teleport instantaneo continuo", playerPage, 7, function(v)
    InstaTeleportEnabled = v
    if v then
        InstaTpConnection = RunService.Stepped:Connect(function()
            if SelectedPlayer then
                pcall(function()
                    local target = Players:FindFirstChild(SelectedPlayer)
                    if target and target.Character then
                        LocalPlayer.Character.HumanoidRootPart.CFrame = target.Character.HumanoidRootPart.CFrame * CFrame.new(0, YOffset, 0)
                        LocalPlayer.Character.HumanoidRootPart.Velocity = Vector3.new(0,0,0)
                    end
                end)
            end
        end)
    else
        if InstaTpConnection then InstaTpConnection:Disconnect(); InstaTpConnection = nil end
    end
end)

addSliderRow("Y Offset", 0, 500, 0, playerPage, 8, function(val)
    YOffset = val
end)

addToggleRow("Spectate", "Ver camara de otro jugador", playerPage, 9, function(v)
    SpectateEnabled = v
    if v then
        SpectateConnection = RunService.RenderStepped:Connect(function()
            if SelectedPlayer then
                local target = Players:FindFirstChild(SelectedPlayer)
                if target and target.Character and target.Character:FindFirstChild("Humanoid") then
                    workspace.CurrentCamera.CameraSubject = target.Character.Humanoid
                end
            end
        end)
    else
        if SpectateConnection then SpectateConnection:Disconnect(); SpectateConnection = nil end
        pcall(function() workspace.CurrentCamera.CameraSubject = LocalPlayer.Character.Humanoid end)
    end
end)

addSectionTitle("Orbit & Tracker", playerPage, 10)

addToggleRow("Orbit Attack", "Orbitar alrededor del enemigo", playerPage, 11, function(v)
    OrbitEnabled = v
end)

addSliderRow("Orbit Distancia", 2, 50, 5, playerPage, 12, function(val)
    OrbitDistance = val
end)

addSliderRow("Orbit Altura", 2, 350, 2, playerPage, 13, function(val)
    OrbitHeight = val
end)


-- ============================================================
--  FUNCIONES EXTRA PAGE (Fruit Attacks, V4, Invisible)
-- ============================================================
addSectionTitle("Ataques de Fruta", extraPage, 1)

addToggleRow("Fruit Attack (Kitsune)", "Ultra Speed - LeftClickRemote", extraPage, 2, function(v)
    FruitAttackKitsune = v
    if v then
        task.spawn(function()
            while FruitAttackKitsune do
                task.wait(0.001)
                pcall(function()
                    local targetPlayer = GetNearestPlayer()
                    if targetPlayer and targetPlayer.Character and LocalPlayer.Character then
                        local tool = LocalPlayer.Character:FindFirstChild("Kitsune-Kitsune")
                        if tool then
                            local direction = (targetPlayer.Character.HumanoidRootPart.Position - LocalPlayer.Character.HumanoidRootPart.Position).Unit
                            tool:WaitForChild("LeftClickRemote"):FireServer(direction, 1, true)
                        end
                    end
                end)
            end
        end)
    end
end)

addToggleRow("Fruit Attack (T-Rex)", "Ultra Speed - LeftClickRemote", extraPage, 3, function(v)
    FruitAttackTRex = v
    if v then
        task.spawn(function()
            while FruitAttackTRex do
                task.wait(0.001)
                pcall(function()
                    local targetPlayer = GetNearestPlayer()
                    if targetPlayer and targetPlayer.Character and LocalPlayer.Character then
                        local tool = LocalPlayer.Character:FindFirstChild("T-Rex-T-Rex")
                        if tool then
                            local direction = (targetPlayer.Character.HumanoidRootPart.Position - LocalPlayer.Character.HumanoidRootPart.Position).Unit
                            tool:WaitForChild("LeftClickRemote"):FireServer(direction, 1)
                        end
                    end
                end)
            end
        end)
    end
end)

addSectionTitle("Automatizacion", extraPage, 4)

addToggleRow("Auto V4 Awakening", "Activa awakening automaticamente", extraPage, 5, function(v)
    AutoAwakening = v
    if v then
        if v4Connection then pcall(function() task.cancel(v4Connection) end) end
        v4Connection = task.spawn(function()
            while AutoAwakening do
                task.wait(0.5)
                pcall(function()
                    local tool = LocalPlayer.Backpack:FindFirstChild("Awakening") or (LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("Awakening"))
                    if tool and tool:FindFirstChild("RemoteFunction") then
                        tool.RemoteFunction:InvokeServer(true)
                    end
                end)
            end
        end)
    else
        if v4Connection then pcall(function() task.cancel(v4Connection) end); v4Connection = nil end
    end
end)

addSectionTitle("Otros", extraPage, 6)

addToggleRow("Modo Invisible", "Destruye LowerTorso.Root", extraPage, 7, function(v)
    if v then
        local function destroyRoot()
            local char = LocalPlayer.Character
            if not char then return false end
            local lt = char:FindFirstChild("LowerTorso")
            if lt then
                local root = lt:FindFirstChild("Root")
                if root then root:Destroy(); return true end
            end
            return false
        end
        if destroyRoot() then
            addNotification("Invisible", "Modo invisible activado", C.green)
        else
            -- Esperar a que cargue el personaje y reintentar
            task.spawn(function()
                local char = LocalPlayer.Character or LocalPlayer.CharacterAdded:Wait()
                task.wait(1)
                if char and char:FindFirstChild("LowerTorso") then
                    local root = char.LowerTorso:FindFirstChild("Root")
                    if root then root:Destroy(); addNotification("Invisible", "Modo invisible activado", C.green)
                    else addNotification("Invisible", "No se encontro LowerTorso.Root", C.orange) end
                else addNotification("Invisible", "No se encontro LowerTorso", C.orange) end
            end)
        end
    end
end)

addSectionTitle("Profile Showcase", extraPage, 8)

-- Showcase state
local ShowcaseSlot = 1
local ShowcaseItemId = 786
local ShowcaseItemName = "Pirate King"

local ShowcaseItems = {
    {name = "Pirate King",          id = 786},
    {name = "Le Antigua",           id = 65},
    {name = "Super Ultra Pain",     id = 478},
    {name = "Cotton Candy Pain",    id = 478},
    {name = "YouTuber",             id = 680},
    {name = "Pink Portal",          id = 458},
    {name = "Equal to the Heaven",  id = 737},
    {name = "Dragon Fisica",        id = 254},
}

local slotNames = {"Slot 1", "Slot 2", "Slot 3", "Slot 4", "Slot 5", "Slot 6"}
addDropdownRow("Slot", slotNames, extraPage, 9, function(opt)
    ShowcaseSlot = tonumber(opt:match("%d+")) or 1
end)

local itemNames = {}
for _, item in ipairs(ShowcaseItems) do table.insert(itemNames, item.name) end
addDropdownRow("Item", itemNames, extraPage, 10, function(opt)
    for _, item in ipairs(ShowcaseItems) do
        if item.name == opt then
            ShowcaseItemId = item.id
            ShowcaseItemName = item.name
            break
        end
    end
end)

addButtonRow("Aplicar Showcase", extraPage, 11, function()
    pcall(function()
        local args = {"Showcase", ShowcaseSlot, ShowcaseItemId}
        game:GetService("ReplicatedStorage"):WaitForChild("Remotes"):WaitForChild("UpdatePlayerProfileValue"):InvokeServer(unpack(args))
    end)
    addNotification("Showcase", ShowcaseItemName .. " en Slot " .. ShowcaseSlot, C.green)
end)

-- ============================================================
--  VISUAL PAGE
-- ============================================================
addSectionTitle("ESP", visualPage, 1)

addToggleRow("ESP Jugadores + NPCs", "Nombres sobre cabeza (BillboardGui)", visualPage, 2, function(on)
    ESPEnabled = on; UpdateESP()
end)

addToggleRow("ESP Drawing", "Con distancia en metros (Drawing API)", visualPage, 3, function(on)
    ESPDrawingEnabled = on
end)

-- ESP Drawing system (de Azucar hub - usa Drawing API)
local drawingESPConnections = {}
local function CreateDrawingESP(plr)
    local NameTag = Drawing.new("Text")
    NameTag.Visible = false; NameTag.Center = true; NameTag.Outline = true
    NameTag.Font = 2; NameTag.Size = 14; NameTag.Color = C.accent

    local connection
    connection = RunService.RenderStepped:Connect(function()
        if ESPDrawingEnabled and plr and plr.Parent and plr.Character and plr.Character:FindFirstChild("HumanoidRootPart") and plr ~= LocalPlayer then
            local hrp = plr.Character.HumanoidRootPart
            local pos, onScreen = workspace.CurrentCamera:WorldToViewportPoint(hrp.Position + Vector3.new(0, 3, 0))
            if onScreen then
                local myHRP = LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
                local dist = myHRP and math.floor((myHRP.Position - hrp.Position).Magnitude) or 0
                NameTag.Position = Vector2.new(pos.X, pos.Y)
                NameTag.Text = plr.Name .. " [" .. dist .. "m]"
                NameTag.Visible = true
            else
                NameTag.Visible = false
            end
        else
            NameTag.Visible = false
            if not plr or not plr.Parent then
                NameTag:Remove(); connection:Disconnect()
            end
        end
    end)
    table.insert(drawingESPConnections, connection)
end

for _, v in pairs(Players:GetPlayers()) do
    if v ~= LocalPlayer then CreateDrawingESP(v) end
end
Players.PlayerAdded:Connect(function(plr) CreateDrawingESP(plr) end)

-- ESP refresh loop
task.spawn(function()
    while true do task.wait(5); if ESPEnabled then UpdateESP() end end
end)

addSectionTitle("Rendimiento", visualPage, 4)

-- FPS Booster button
local fpsBtn = Instance.new("TextButton", visualPage)
fpsBtn.Size = UDim2.new(1, 0, 0, 48); fpsBtn.BackgroundColor3 = C.item; fpsBtn.Text = ""
fpsBtn.LayoutOrder = 6; fpsBtn.ClipsDescendants = true
corner(8, fpsBtn); local fpsStroke = stroke(C.border, 1, fpsBtn)
trackTheme(fpsBtn, "BackgroundColor3", "item"); trackTheme(fpsStroke, "Color", "border")

local fpsTitle = label({Text = "FPS Booster", Font = Enum.Font.GothamSemibold, TextSize = 13, TextColor3 = C.text,
    Size = UDim2.new(1, -20, 0, 20), Position = UDim2.new(0, 10, 0, 6)}, fpsBtn)
trackTheme(fpsTitle, "TextColor3", "text")
local fpsSubLabel = label({Text = "Presiona para ejecutar",
    Font = Enum.Font.Gotham, TextSize = 10, TextColor3 = C.sub,
    Size = UDim2.new(1, -20, 0, 14), Position = UDim2.new(0, 10, 0, 27)}, fpsBtn)

local fpsDot = Instance.new("Frame", fpsBtn)
fpsDot.Size = UDim2.new(0, 7, 0, 7); fpsDot.Position = UDim2.new(1, -18, 0.5, -3)
fpsDot.BackgroundColor3 = C.sub; corner(99, fpsDot)

fpsBtn.MouseEnter:Connect(function() tween(fpsBtn, 0.08, {BackgroundColor3 = C.itemHov}) end)
fpsBtn.MouseLeave:Connect(function() tween(fpsBtn, 0.08, {BackgroundColor3 = C.item}) end)

fpsBtn.MouseButton1Click:Connect(function()
    fpsSubLabel.Text = "Cargando..."; tween(fpsDot, 0.3, {BackgroundColor3 = C.orange})
    task.spawn(function()
        local ok = pcall(function()
            loadstring(game:HttpGet("https://raw.githubusercontent.com/CasperFlyModz/discord.gg-rips/main/FPSBooster.lua"))()
        end)
        if ok then
            tween(fpsDot, 0.3, {BackgroundColor3 = C.green}); fpsSubLabel.Text = "FPS Booster activo"
            fpsSubLabel.TextColor3 = C.green; addNotification("FPS Booster", "Ejecutado correctamente", C.green)
        else
            fpsSubLabel.Text = "Error al ejecutar"; fpsSubLabel.TextColor3 = C.red
            tween(fpsDot, 0.3, {BackgroundColor3 = C.red})
        end
    end)
end)

addSectionTitle("Efectos Visuales", visualPage, 7)

addToggleRow("Full Bright", "Iluminacion maxima", visualPage, 8, function(on)
    FullBrightEnabled = on
    if not on then
        pcall(function()
            game.Lighting.Ambient = Color3.fromRGB(0, 0, 0)
            game.Lighting.ClockTime = 14; game.Lighting.FogEnd = 100000
        end)
    end
end)

addToggleRow("Modo Plastico", "Cambiar materiales a SmoothPlastic", visualPage, 9, function(on)
    if on then
        for _, v in pairs(game:GetDescendants()) do
            if v:IsA("Part") then pcall(function() v.Material = Enum.Material.SmoothPlastic end) end
        end
        addNotification("Visual", "Modo plastico activado", C.accent)
    end
end)

-- ============================================================
--  MOVIMIENTO PAGE
-- ============================================================
addSectionTitle("Movimiento", movePage, 1)

addToggleRow("Infinite Jump", nil, movePage, 2, function(on) iJ = on end)

addToggleRow("No Clip", "Desactiva colisiones", movePage, 3, function(on) ncl = on end)

addToggleRow("Walk on Water", "Smart height Y=9.2", movePage, 4, function(on)
    walkWaterEnabled = on
    if not on and workspace:FindFirstChild("RivalsPremiumWater") then
        workspace.RivalsPremiumWater:Destroy()
    end
end)

addToggleRow("Fly V6", "Abre panel de vuelo", movePage, 5, function(on)
    if on then
        if flyGui then flyGui:Destroy(); flyGui = nil end
        task.spawn(function()
            local player = LocalPlayer
            local main = Instance.new("ScreenGui")
            main.Name = "FlyV6_RivalsPremium"; main.Parent = player:WaitForChild("PlayerGui")
            main.ResetOnSpawn = false; main.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
            flyGui = main

            local Frame = Instance.new("Frame", main)
            Frame.BackgroundColor3 = Color3.fromRGB(163, 255, 137); Frame.BorderColor3 = Color3.fromRGB(103, 221, 213)
            Frame.Position = UDim2.new(0.1, 0, 0.38, 0); Frame.Size = UDim2.new(0, 190, 0, 57)
            Frame.Active = true; Frame.Draggable = true

            local up = Instance.new("TextButton", Frame)
            up.BackgroundColor3 = Color3.fromRGB(79, 255, 152); up.Size = UDim2.new(0, 44, 0, 28)
            up.Font = Enum.Font.SourceSans; up.Text = "UP"; up.TextColor3 = Color3.new(0,0,0); up.TextSize = 14

            local down = Instance.new("TextButton", Frame)
            down.BackgroundColor3 = Color3.fromRGB(215, 255, 121); down.Position = UDim2.new(0, 0, 0.491, 0)
            down.Size = UDim2.new(0, 44, 0, 28)
            down.Font = Enum.Font.SourceSans; down.Text = "DOWN"; down.TextColor3 = Color3.new(0,0,0); down.TextSize = 14

            local onof = Instance.new("TextButton", Frame)
            onof.BackgroundColor3 = Color3.fromRGB(255, 249, 74); onof.Position = UDim2.new(0.7, 0, 0.491, 0)
            onof.Size = UDim2.new(0, 56, 0, 28)
            onof.Font = Enum.Font.SourceSans; onof.Text = "fly"; onof.TextColor3 = Color3.new(0,0,0); onof.TextSize = 14

            local titleLbl = Instance.new("TextLabel", Frame)
            titleLbl.BackgroundColor3 = Color3.fromRGB(242, 60, 255); titleLbl.Position = UDim2.new(0.469, 0, 0, 0)
            titleLbl.Size = UDim2.new(0, 100, 0, 28)
            titleLbl.Font = Enum.Font.SourceSans; titleLbl.Text = "FLY V6 Premium"
            titleLbl.TextColor3 = Color3.new(0,0,0); titleLbl.TextScaled = true

            local plus = Instance.new("TextButton", Frame)
            plus.BackgroundColor3 = Color3.fromRGB(133, 145, 255); plus.Position = UDim2.new(0.231, 0, 0, 0)
            plus.Size = UDim2.new(0, 45, 0, 28)
            plus.Font = Enum.Font.SourceSans; plus.Text = "+"; plus.TextColor3 = Color3.new(0,0,0)
            plus.TextScaled = true

            local speedLbl = Instance.new("TextLabel", Frame)
            speedLbl.BackgroundColor3 = Color3.fromRGB(255, 85, 0); speedLbl.Position = UDim2.new(0.468, 0, 0.491, 0)
            speedLbl.Size = UDim2.new(0, 44, 0, 28)
            speedLbl.Font = Enum.Font.SourceSans; speedLbl.Text = "1"; speedLbl.TextColor3 = Color3.new(0,0,0)
            speedLbl.TextScaled = true

            local mine = Instance.new("TextButton", Frame)
            mine.BackgroundColor3 = Color3.fromRGB(123, 255, 247); mine.Position = UDim2.new(0.231, 0, 0.491, 0)
            mine.Size = UDim2.new(0, 45, 0, 29)
            mine.Font = Enum.Font.SourceSans; mine.Text = "-"; mine.TextColor3 = Color3.new(0,0,0)
            mine.TextScaled = true

            local closebutton = Instance.new("TextButton", Frame)
            closebutton.BackgroundColor3 = Color3.fromRGB(225, 25, 0); closebutton.Font = Enum.Font.SourceSans
            closebutton.Size = UDim2.new(0, 45, 0, 28); closebutton.Text = "X"; closebutton.TextSize = 30
            closebutton.TextColor3 = Color3.fromRGB(255, 255, 255); closebutton.Position = UDim2.new(0, 0, -1, 27)

            local mini = Instance.new("TextButton", Frame)
            mini.BackgroundColor3 = Color3.fromRGB(133, 145, 255); mini.Font = Enum.Font.SourceSans
            mini.Size = UDim2.new(0, 45, 0, 28); mini.Text = "-"; mini.TextSize = 24
            mini.TextColor3 = Color3.new(0,0,0); mini.Position = UDim2.new(0, 44, -1, 27)

            local mini2 = Instance.new("TextButton", Frame)
            mini2.BackgroundColor3 = Color3.fromRGB(133, 145, 255); mini2.Font = Enum.Font.SourceSans
            mini2.Size = UDim2.new(0, 45, 0, 28); mini2.Text = "+"; mini2.TextSize = 24
            mini2.TextColor3 = Color3.new(0,0,0); mini2.Position = UDim2.new(0, 44, -1, 57)
            mini2.Visible = false

            local flySpeed = 1; local flyActive = false; local tpwalking = false
            local bodyVelocity2, bodyGyro2, flyConn, upConn, downConn = nil, nil, nil, nil, nil

            local function startFly()
                local char = player.Character; if not char then return end
                local hum = char:FindFirstChild("Humanoid"); local root = char:FindFirstChild("HumanoidRootPart")
                if not hum or not root then return end
                flyActive = true; hum.PlatformStand = true
                local anim = char:FindFirstChild("Animate"); if anim then anim.Disabled = true end
                for i = 1, flySpeed do
                    task.spawn(function()
                        tpwalking = true; local chr = player.Character; local h = chr and chr:FindFirstChild("Humanoid")
                        while tpwalking and chr and h and h.Parent do
                            RunService.Heartbeat:Wait()
                            if h.MoveDirection.Magnitude > 0 then chr:TranslateBy(h.MoveDirection) end
                        end
                    end)
                end
                local states = {
                    Enum.HumanoidStateType.Climbing, Enum.HumanoidStateType.FallingDown,
                    Enum.HumanoidStateType.Flying, Enum.HumanoidStateType.Freefall,
                    Enum.HumanoidStateType.GettingUp, Enum.HumanoidStateType.Jumping,
                    Enum.HumanoidStateType.Landed, Enum.HumanoidStateType.Physics,
                    Enum.HumanoidStateType.PlatformStanding, Enum.HumanoidStateType.Ragdoll,
                    Enum.HumanoidStateType.Running, Enum.HumanoidStateType.RunningNoPhysics,
                    Enum.HumanoidStateType.Seated, Enum.HumanoidStateType.StrafingNoPhysics,
                    Enum.HumanoidStateType.Swimming,
                }
                for _, s in ipairs(states) do hum:SetStateEnabled(s, false) end
                hum:ChangeState(Enum.HumanoidStateType.Swimming)
                local torso = char:FindFirstChild("Torso") or char:FindFirstChild("UpperTorso")
                if torso then
                    bodyGyro2 = Instance.new("BodyGyro", torso)
                    bodyGyro2.P = 9e4; bodyGyro2.MaxTorque = Vector3.new(9e9, 9e9, 9e9); bodyGyro2.CFrame = torso.CFrame
                    bodyVelocity2 = Instance.new("BodyVelocity", torso)
                    bodyVelocity2.Velocity = Vector3.new(0, 0.1, 0); bodyVelocity2.MaxForce = Vector3.new(9e9, 9e9, 9e9)
                end
                local ctrl = {f=0,b=0,l=0,r=0}; local lastctrl = {f=0,b=0,l=0,r=0}; local maxspeed = 50; local currentSpeed = 0
                flyConn = RunService.Heartbeat:Connect(function()
                    if not flyActive or not player.Character then return end
                    local t = player.Character:FindFirstChild("Torso") or player.Character:FindFirstChild("UpperTorso")
                    if not t or not bodyVelocity2 or not bodyGyro2 then return end
                    ctrl.f = UserInputService:IsKeyDown(Enum.KeyCode.W) and 1 or 0
                    ctrl.b = UserInputService:IsKeyDown(Enum.KeyCode.S) and -1 or 0
                    ctrl.r = UserInputService:IsKeyDown(Enum.KeyCode.D) and 1 or 0
                    ctrl.l = UserInputService:IsKeyDown(Enum.KeyCode.A) and -1 or 0
                    local mv, ms = ctrl.f + ctrl.b, ctrl.l + ctrl.r
                    if mv ~= 0 or ms ~= 0 then currentSpeed = math.min(currentSpeed + 0.5 + currentSpeed/maxspeed, maxspeed)
                    else currentSpeed = math.max(currentSpeed - 1, 0) end
                    local cam = workspace.CurrentCamera
                    if mv ~= 0 or ms ~= 0 then
                        bodyVelocity2.Velocity = (cam.CFrame.LookVector*mv + cam.CFrame.RightVector*ms) * currentSpeed
                        lastctrl = {f=ctrl.f,b=ctrl.b,l=ctrl.l,r=ctrl.r}
                    elseif currentSpeed ~= 0 then
                        bodyVelocity2.Velocity = (cam.CFrame.LookVector*(lastctrl.f+lastctrl.b) + cam.CFrame.RightVector*(lastctrl.l+lastctrl.r)) * currentSpeed
                    else bodyVelocity2.Velocity = Vector3.new(0,0,0) end
                    bodyGyro2.CFrame = cam.CFrame * CFrame.Angles(-math.rad(mv*50*currentSpeed/maxspeed), 0, 0)
                    if UserInputService:IsKeyDown(Enum.KeyCode.Space) then bodyVelocity2.Velocity += Vector3.new(0, 30, 0) end
                    if UserInputService:IsKeyDown(Enum.KeyCode.LeftControl) then bodyVelocity2.Velocity -= Vector3.new(0, 30, 0) end
                end)
            end

            local function stopFly()
                flyActive = false; tpwalking = false
                if flyConn then flyConn:Disconnect(); flyConn = nil end
                local char = player.Character
                if char then
                    local hum = char:FindFirstChild("Humanoid")
                    if hum then
                        hum.PlatformStand = false
                        local states = {
                            Enum.HumanoidStateType.Climbing, Enum.HumanoidStateType.FallingDown,
                            Enum.HumanoidStateType.Flying, Enum.HumanoidStateType.Freefall,
                            Enum.HumanoidStateType.GettingUp, Enum.HumanoidStateType.Jumping,
                            Enum.HumanoidStateType.Landed, Enum.HumanoidStateType.Physics,
                            Enum.HumanoidStateType.PlatformStanding, Enum.HumanoidStateType.Ragdoll,
                            Enum.HumanoidStateType.Running, Enum.HumanoidStateType.RunningNoPhysics,
                            Enum.HumanoidStateType.Seated, Enum.HumanoidStateType.StrafingNoPhysics,
                            Enum.HumanoidStateType.Swimming,
                        }
                        for _, s in ipairs(states) do hum:SetStateEnabled(s, true) end
                        hum:ChangeState(Enum.HumanoidStateType.RunningNoPhysics)
                    end
                    local anim2 = char:FindFirstChild("Animate"); if anim2 then anim2.Disabled = false end
                    if bodyVelocity2 then bodyVelocity2:Destroy(); bodyVelocity2 = nil end
                    if bodyGyro2 then bodyGyro2:Destroy(); bodyGyro2 = nil end
                end
            end

            onof.MouseButton1Click:Connect(function()
                if flyActive then stopFly(); onof.Text = "fly" else startFly(); onof.Text = "STOP" end
            end)
            up.MouseButton1Down:Connect(function()
                upConn = RunService.Heartbeat:Connect(function()
                    local root = player.Character and player.Character:FindFirstChild("HumanoidRootPart")
                    if root then root.CFrame = root.CFrame * CFrame.new(0, 1.5, 0) end
                end)
            end)
            up.MouseButton1Up:Connect(function() if upConn then upConn:Disconnect(); upConn = nil end end)
            up.MouseLeave:Connect(function() if upConn then upConn:Disconnect(); upConn = nil end end)
            down.MouseButton1Down:Connect(function()
                downConn = RunService.Heartbeat:Connect(function()
                    local root = player.Character and player.Character:FindFirstChild("HumanoidRootPart")
                    if root then root.CFrame = root.CFrame * CFrame.new(0, -1.5, 0) end
                end)
            end)
            down.MouseButton1Up:Connect(function() if downConn then downConn:Disconnect(); downConn = nil end end)
            down.MouseLeave:Connect(function() if downConn then downConn:Disconnect(); downConn = nil end end)
            plus.MouseButton1Click:Connect(function()
                flySpeed = flySpeed + 1; speedLbl.Text = tostring(flySpeed)
                if flyActive then stopFly(); task.wait(0.1); startFly() end
            end)
            mine.MouseButton1Click:Connect(function()
                if flySpeed > 1 then flySpeed = flySpeed - 1; speedLbl.Text = tostring(flySpeed)
                    if flyActive then stopFly(); task.wait(0.1); startFly() end end
            end)
            closebutton.MouseButton1Click:Connect(function() stopFly(); main:Destroy(); flyGui = nil end)
            mini.MouseButton1Click:Connect(function()
                for _, v in ipairs({up,down,onof,plus,speedLbl,mine,mini}) do v.Visible = false end
                mini2.Visible = true; Frame.BackgroundTransparency = 1; closebutton.Position = UDim2.new(0, 0, -1, 57)
            end)
            mini2.MouseButton1Click:Connect(function()
                for _, v in ipairs({up,down,onof,plus,speedLbl,mine,mini}) do v.Visible = true end
                mini2.Visible = false; Frame.BackgroundTransparency = 0; closebutton.Position = UDim2.new(0, 0, -1, 27)
            end)
            player.CharacterAdded:Connect(function()
                if flyActive then stopFly(); task.wait(0.5); startFly() end
            end)
        end)
    else
        if flyGui then flyGui:Destroy(); flyGui = nil end
    end
end)

addSectionTitle("Config.", movePage, 6)

addToggleRow("Speed Hack", "Activa velocidad", movePage, 7, function(on) sAct = on end)

addSliderRow("Velocidad", 16, 500, 16, movePage, 8, function(val) sVal = val end)

-- ============================================================
--  TELEPORT PAGE (~40 ubicaciones)
-- ============================================================
local function doTP(x, y, z)
    local char = LocalPlayer.Character
    if char then char:PivotTo(CFrame.new(x, y, z)) end
end

-- TELEPORTS ORIGINALES
addSectionTitle("Teleports", tpPage, 1)
addTpButton("Barco Maldito", "923, 126, 32852", Color3.fromRGB(0, 220, 140), tpPage, 2, function() doTP(923, 126, 32852) end)
addTpButton("Castillo", "-5085, 316, -3156", Color3.fromRGB(123, 136, 255), tpPage, 3, function() doTP(-5085, 316, -3156) end)
addTpButton("Mansion", "-12463, 375, -7523", Color3.fromRGB(255, 170, 68), tpPage, 4, function() doTP(-12463, 375, -7523) end)

-- ============================================================
--  SETTINGS PAGE (Colores + Seguridad)
-- ============================================================
addSectionTitle("Colores", settingsPage, 1)

local colorNames = {}
for _, p in ipairs(ColorPresets) do table.insert(colorNames, p.name) end

addDropdownRow("Color Primario", colorNames, settingsPage, 2, function(name)
    SavedPrimary = name
    ApplyColorChange()
    addNotification("Colores", "Primario: " .. name, getPresetColor(name))
end)

addDropdownRow("Color Secundario", colorNames, settingsPage, 3, function(name)
    SavedSecondary = name
    ApplyColorChange()
    addNotification("Colores", "Secundario: " .. name, getPresetColor(name))
end)

addSectionTitle("Reset", settingsPage, 5)

addButtonRow("Reset Colores (Default)", settingsPage, 6, function()
    SavedPrimary = DEFAULT_PRIMARY
    SavedSecondary = DEFAULT_SECONDARY
    ApplyColorChange()
    addNotification("Colores", "Colores restaurados a default", C.accent)
end)

addSectionTitle("Seguridad", settingsPage, 8)

addButtonRow("Activar Anti-Kick", settingsPage, 9, function()
    pcall(function()
        local OldNamecall
        OldNamecall = hookmetamethod(game, "__namecall", newcclosure(function(Self, ...)
            local Method = getnamecallmethod()
            if (Method == "Kick" or Method == "kick") and Self == LocalPlayer then
                task.spawn(function()
                    if #Players:GetPlayers() <= 1 then
                        TeleportService:Teleport(game.PlaceId, LocalPlayer)
                    else
                        TeleportService:TeleportToPlaceInstance(game.PlaceId, game.JobId, LocalPlayer)
                    end
                end)
                return nil
            end
            return OldNamecall(Self, ...)
        end))
    end)
    addNotification("Seguridad", "Anti-Kick activado + Auto Rejoin", C.green)
end)

addButtonRow("Activar Anti-AFK", settingsPage, 10, function()
    pcall(function()
        local vu = game:GetService("VirtualUser")
        LocalPlayer.Idled:Connect(function()
            vu:Button2Down(Vector2.new(0,0), workspace.CurrentCamera.CFrame)
            task.wait(1)
            vu:Button2Up(Vector2.new(0,0), workspace.CurrentCamera.CFrame)
        end)
    end)
    addNotification("Seguridad", "Anti-AFK activado", C.green)
end)

-- ============================================================
--  RUNSERVICE LOOPS
-- ============================================================

-- Aimlock Q key toggle
UserInputService.InputBegan:Connect(function(input, gp)
    if gp then return end
    if input.KeyCode == Enum.KeyCode.Q then
        if AimlockEnabled then
            if u4 then u4 = false; u19 = nil
            else u19 = FindNearestEnemy(); u4 = true end
        end
    end
    -- RightShift toggle GUI
    if input.KeyCode == Enum.KeyCode.RightShift then
        mainFrame.Visible = not mainFrame.Visible
    end
end)

-- Infinite Jump
UserInputService.JumpRequest:Connect(function()
    if iJ then
        local hum = LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("Humanoid")
        if hum then hum:ChangeState(Enum.HumanoidStateType.Jumping) end
    end
end)

-- No Clip
RunService.Stepped:Connect(function()
    if ncl and LocalPlayer.Character then
        for _, v in pairs(LocalPlayer.Character:GetDescendants()) do
            if v:IsA("BasePart") then v.CanCollide = false end
        end
    end
end)

-- Speed
RunService.Heartbeat:Connect(function()
    if sAct and LocalPlayer.Character then
        local hum = LocalPlayer.Character:FindFirstChild("Humanoid")
        if hum and hum.MoveDirection.Magnitude > 0 then
            LocalPlayer.Character:TranslateBy(hum.MoveDirection * (sVal / 55))
        end
    end
end)

-- Walk on Water
RunService.RenderStepped:Connect(function()
    local char = LocalPlayer.Character
    local hrp = char and char:FindFirstChild("HumanoidRootPart")
    if walkWaterEnabled and hrp then
        if hrp.Position.Y >= 9.5 and hrp.Velocity.Y <= 0 then
            local waterPart = workspace:FindFirstChild("RivalsPremiumWater")
            if not waterPart then
                waterPart = Instance.new("Part", workspace)
                waterPart.Name = "RivalsPremiumWater"
                waterPart.Size = Vector3.new(20, 1, 20)
                waterPart.Transparency = 1; waterPart.Anchored = true
                waterPart.CanCollide = true; waterPart.CanQuery = false
            end
            waterPart.CFrame = CFrame.new(hrp.Position.X, 9.2, hrp.Position.Z)
        else
            if workspace:FindFirstChild("RivalsPremiumWater") then workspace.RivalsPremiumWater:Destroy() end
        end
    else
        if workspace:FindFirstChild("RivalsPremiumWater") then workspace.RivalsPremiumWater:Destroy() end
    end
end)

-- Full Bright loop
RunService.Heartbeat:Connect(function()
    if FullBrightEnabled then
        pcall(function()
            game.Lighting.Ambient = Color3.fromRGB(255, 255, 255)
            game.Lighting.ClockTime = 14; game.Lighting.FogEnd = 9e9
        end)
    end
end)

-- Orbit + Tracker loop
task.spawn(function()
    while true do
        task.wait(0.01)
        pcall(function()
            local char = LocalPlayer.Character
            local root = char and char:FindFirstChild("HumanoidRootPart")
            if not root then return end

            local target = SelectedPlayer and Players:FindFirstChild(SelectedPlayer)

            if OrbitEnabled and target and target.Character and target.Character:FindFirstChild("HumanoidRootPart") then
                rot = rot + 0.15
                root.CFrame = target.Character.HumanoidRootPart.CFrame * CFrame.Angles(0, rot, 0) * CFrame.new(OrbitDistance, OrbitHeight, 0)
            end
        end)
    end
end)

-- ============================================================
--  WINDOW CONTROLS
-- ============================================================
local minimized = false
local miniSize = UDim2.new(0, 180, 0, TITLEBAR_H)

minBtn.MouseButton1Click:Connect(function()
    minimized = not minimized
    if minimized then
        -- Hide content immediately, then shrink
        sidebar.Visible = false; sidebarLine.Visible = false
        contentFrame.Visible = false; titleLine.Visible = false
        premiumBadge.Visible = false
        minBtn.Text = "+"
        tween(mainFrame, 0.2, {Size = miniSize})
    else
        -- Expand first, then show content
        local sz = guiSizes[currentGuiSize]
        minBtn.Text = "-"
        tween(mainFrame, 0.2, {Size = UDim2.new(0, sz.w, 0, sz.h)})
        task.delay(0.2, function()
            sidebar.Visible = true; sidebarLine.Visible = true
            contentFrame.Visible = true; titleLine.Visible = true
            premiumBadge.Visible = true
        end)
    end
end)

closeBtn.MouseButton1Click:Connect(function()
    ESPEnabled = false; ClearESP(); ESPDrawingEnabled = false
    if workspace:FindFirstChild("RivalsPremiumWater") then workspace.RivalsPremiumWater:Destroy() end
    tween(mainFrame, 0.15, {BackgroundTransparency = 1})
    task.wait(0.18); screenGui:Destroy()
end)

-- ============================================================
--  ANIMATED GRADIENT (banner glow cycles between primary & secondary)
-- ============================================================
task.spawn(function()
    local toggle = true
    while bannerGlow and bannerGlow.Parent do
        toggle = not toggle
        local targetColor = toggle and C.accent or C.accent2
        tween(bannerGlow, 1.5, {BackgroundColor3 = targetColor})
        task.wait(1.5)
    end
end)

-- ============================================================
--  INIT
-- ============================================================
showPage("Home")
addNotification("Rivals Hub Premium", "v3.0 cargado correctamente", C.accent)
